services:
  - type: web
    name: bot-formularios-prod
    env: python
    region: ohio
    plan: free

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install chromium

    startCommand: |
      gunicorn app:app \
        --bind 0.0.0.0:$PORT \
        --workers 1 \
        --threads 4 \
        --timeout 180

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0


    autoDeploy: true
